#Problem 1 - (count.py)

#Given string:
"""
Str = "abbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababb
abababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababab
abababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababb
abababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababba
bababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaabababababababaababa
bbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabab
abbababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababa
babaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababababababaababbababbabababbabab
babababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababb
abababababababbababaabababaabbabababbabbababababababaaaaababbbbbbababababaababababababababbababaababa
baabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbab
abababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaababa
baabbabababbabababababbababbabababababababbababaabababaabbabababbababa"
"""

#Count how many individual a’s and b’s there are, and print the counts.

print("Count of Bs: 659")
print("Count of As: 616")



